
package view;

import java.util.HashSet;

/**
 *
 * @author conta
 */
public class ClienteView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteView.class.getName());

    Controller.ClienteController control = new Controller.ClienteController();
    
    private void atualizarTabela(){
        java.util.List<model.Cliente> lista = control.buscarTodos(); //pega lista de cliente do arquivo
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblClientes.getModel(); //modelo da tablea
        modelo.setRowCount(0); //limpa a tabela antes de começar
        
        for (model.Cliente c : lista){
            modelo.addRow(new Object[]{c.getId_cliente(), c.getNome()});
        }
        
        txtId.setText(String.valueOf(control.gerarProximoId()));
    }
    
  
    public ClienteView() {
        initComponents();
        this.setLocationRelativeTo(null); //centraliza a tela no meio com referencia a tela sendo utilizada
        this.getRootPane().setDefaultButton(btnSalvar); //salvar com enter
        atualizarTabela();
        this.getContentPane().setBackground(new java.awt.Color(245,245,245)); //cor da tela de fundo
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnAlterar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnListaTodos = new javax.swing.JButton();
        btnStatus = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CLIENTES");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID: ");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtId.setEditable(false);
        txtId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nome: ");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSalvar.setBackground(new java.awt.Color(200, 255, 200));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 100, 0));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnExcluir.setBackground(new java.awt.Color(255, 200, 200));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(150, 0, 0));
        btnExcluir.setText("Excluir");
        btnExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnLimpar.setBackground(new java.awt.Color(230, 230, 230));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(60, 60, 60));
        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ));
        tblClientes.setShowGrid(true);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        btnAlterar.setBackground(new java.awt.Color(255, 240, 200));
        btnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(102, 51, 0));
        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        btnBuscar.setBackground(new java.awt.Color(200, 220, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 51, 153));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnListaTodos.setBackground(new java.awt.Color(200, 220, 255));
        btnListaTodos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListaTodos.setForeground(new java.awt.Color(0, 51, 153));
        btnListaTodos.setText("Listar Todos");
        btnListaTodos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnListaTodos.addActionListener(this::btnListaTodosActionPerformed);

        btnStatus.setText("Status");
        btnStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnVoltar.setBackground(new java.awt.Color(230, 230, 230));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(60, 60, 60));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(318, 318, 318)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnListaTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar)
                    .addComponent(btnAlterar)
                    .addComponent(btnBuscar)
                    .addComponent(btnListaTodos)
                    .addComponent(btnStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        
        String idStr = txtId.getText();
        String nomeAtual = txtNome.getText();
        
        if(idStr.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um cliente na tabela primeiro!");
            return;
        }
        //abrir janelinha pra alterar
        String novoNome = javax.swing.JOptionPane.showInputDialog(this, "Alterar nome do cliente:", nomeAtual);
        
        if(novoNome !=null && !novoNome.trim().isEmpty()){ //verifica se digitou algo e não cancelou
            try {
                int id =Integer.parseInt(idStr);
                control.salvar(id, novoNome); //chama controller e atualiza
                javax.swing.JOptionPane.showMessageDialog(this, "Cliente atualizado com sucesso!");
                atualizarTabela();//recarregar com novo nome
                txtNome.setText("");//limpar o campo do nome
            } catch (Exception e ){
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao alterar: "+ e.getMessage());
            }
        }
    }                                          

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        try {
            String nome = txtNome.getText().trim(); //trim pra ignorar espaços no começo e fim
            //int id = Integer.parseInt(txtId.getText());
            String idStr = txtId.getText();
            
            if (nome.isEmpty()){
                javax.swing.JOptionPane.showMessageDialog(this, "Digite um nome");
                return;
            }
            
            if (!nome.matches("^[a-zA-ZÀ-ÿ\\s]+$")){ //REGEX pra aceitar somente letras, com ou sem acentuação --- não aceita número e caracteres especiais
                javax.swing.JOptionPane.showMessageDialog(this, "O nome deve conter apenas letras!");
                return;
            }
            
            int id= Integer.parseInt(idStr);
            control.salvar(id,nome);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
            
            txtNome.setText(""); //limpando o campo
            atualizarTabela();//atualiza a lista na tela
            btnStatus.setText("Cliente salvo!");
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar: "+ e.getMessage());
        }
    }                                         

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        
        txtNome.setText("");
        txtId.setText(String.valueOf(control.gerarProximoId()));
        btnStatus.setText("Campos resetados");
        atualizarTabela();
    }                                         

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        
        String idStr= txtId.getText();
        String nome= txtNome.getText();
        
        if (idStr.isEmpty()|| nome.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um cliente na tabela para excluir.");
            return;
        }
        
        int id = Integer.parseInt(idStr);
        String mensagem= "Deseja realmente excluir esse cliente?\n\n"+
                "Nome: "+nome+"\n"+
                "ID: "+id;
        
        int confirmacao= javax.swing.JOptionPane.showConfirmDialog(this, mensagem, "Confirmar Exclusão",
                javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirmacao==javax.swing.JOptionPane.YES_OPTION){
            control.excluir(id);
            txtNome.setText("");
            atualizarTabela();
            btnStatus.setText("Cliente "+ id+" excluido.");
        }
    }                                          

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String termo = javax.swing.JOptionPane.showInputDialog("Digite o ID ou Nome para buscar:");
        if (termo != null && !termo.isEmpty()){
            java.util.List<model.Cliente> filtrados = control.buscar(termo); //atualizar só com os filtrados
            if (filtrados.isEmpty()){
                javax.swing.JOptionPane.showMessageDialog(this, "Nenhum cliente encontrado com o termo: "+ termo);
                atualizarTabela();
            } else {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblClientes.getModel();
            modelo.setRowCount(0);
            for (model.Cliente c : filtrados){
                modelo.addRow(new Object[]{c.getId_cliente(), c.getNome()});
            }
            btnStatus.setText("Resultados da busca por: "+ termo);
        }
    }                                         
    }
    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        int linha = tblClientes.getSelectedRow(); //qual linha foi clicada
        txtId.setText(tblClientes.getValueAt(linha,0).toString());//pega o id da tabela e coloca no campo
        txtNome.setText(tblClientes.getValueAt(linha,1).toString()); //pega o nome
    }                                        

    private void btnListaTodosActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        atualizarTabela(); //recarrega
        btnStatus.setText("Lista atualizada."); //feedback visual
    }                                             

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        new view.MenuView().setVisible(true);
        this.dispose(); //vai fechar a janela de cliente.
        
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteView().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListaTodos;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel btnStatus;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    // End of variables declaration                   
}
