
package view;

/**
 *
 * @author vitor
 */
public class ConsultaPedido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaPedido.class.getName());
    private final Controller.PedidoController pedidoCtrl = new Controller.PedidoController();
    /** Campo de busca atual selecionado pelo usuário. */
    private String campoBusca = "cod_pedido";
    
    /**
     * Creates new form ConsultaPedido
     */
    public ConsultaPedido() {
        initComponents();
        this.setLocationRelativeTo(null);
        configurarBotoes();
    }
    private void configurarBotoes() {
        // Botões de seleção de campo
        jButtonId_cliente.addActionListener(e -> { campoBusca = "id_cliente";  jLabel3.setText("Digite o ID do cliente:"); });
        jButtonCod_Pedido.addActionListener(e -> { campoBusca = "cod_pedido"; jLabel3.setText("Digite o código do pedido:"); });
        jButtonData_Pedido.addActionListener(e -> { campoBusca = "dt_pedido";  jLabel3.setText("Digite a data (dd/MM/yyyy):"); });
        jButtonData_Entrega.addActionListener(e -> { campoBusca = "dt_entrega"; jLabel3.setText("Digite a data de entrega (dd/MM/yyyy):"); });

        // Botão e campo de texto de busca
        jButtonBuscar_Pedido.addActionListener(e -> buscarPedidos());
        jTextFieldObjeto.addActionListener(e -> buscarPedidos());

        // Botão Sair
        jButtonSair.addActionListener(e -> {
            new view.PedidoPrincipalView().setVisible(true);
            this.dispose();
        });
    }

    private void buscarPedidos() {
        String termo = jTextFieldObjeto.getText().trim();
        javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) jTablePedido.getModel();
        modelo.setRowCount(0);

        java.util.List<model.Pedido> todos = pedidoCtrl.listar();
        for (model.Pedido p : todos) {
            boolean incluir = false;
            switch (campoBusca) {
                case "id_cliente":  incluir = String.valueOf(p.getIdCliente()).contains(termo); break;
                case "cod_pedido": incluir = String.valueOf(p.getCodPedido()).contains(termo); break;
                case "dt_pedido":  incluir = p.getDtPedido().contains(termo);  break;
                case "dt_entrega": incluir = p.getDtEntrega().contains(termo); break;
                case "vlr_total":  incluir = String.format("%.2f", p.getVlrTotal()).contains(termo); break;
                default:           incluir = true;
            }
            if (incluir) {
                modelo.addRow(new Object[]{
                    p.getCodPedido(), p.getIdCliente(),
                    p.getDtPedido(), p.getDtEntrega(),
                    String.format("R$ %.2f", p.getVlrTotal())
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonId_cliente = new javax.swing.JButton();
        jButtonCod_Pedido = new javax.swing.JButton();
        jButtonData_Pedido = new javax.swing.JButton();
        jButtonData_Entrega = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldObjeto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedido = new javax.swing.JTable();
        jButtonSair = new javax.swing.JButton();
        jButtonBuscar_Pedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CONSULTA PEDIDO");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ESCOLHA SEU OBJETO DE CONSULTA");

        jButtonId_cliente.setBackground(new java.awt.Color(0, 204, 255));
        jButtonId_cliente.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonId_cliente.setForeground(new java.awt.Color(0, 0, 0));
        jButtonId_cliente.setText("ID CLIENTE");

        jButtonCod_Pedido.setBackground(new java.awt.Color(0, 204, 255));
        jButtonCod_Pedido.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonCod_Pedido.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCod_Pedido.setText("CODIGO PEDIDO");

        jButtonData_Pedido.setBackground(new java.awt.Color(0, 204, 255));
        jButtonData_Pedido.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonData_Pedido.setForeground(new java.awt.Color(0, 0, 0));
        jButtonData_Pedido.setText("DATA PEDIDO");

        jButtonData_Entrega.setBackground(new java.awt.Color(0, 204, 255));
        jButtonData_Entrega.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonData_Entrega.setForeground(new java.awt.Color(0, 0, 0));
        jButtonData_Entrega.setText("DATA ENTREGA");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DIGITE SEU OBJETO");

        jTextFieldObjeto.setBackground(new java.awt.Color(153, 153, 153));

        jTablePedido.setBackground(new java.awt.Color(204, 204, 204));
        jTablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "COD PEDIDO", "ID CLIENTE", "DATA PEDIDO", "DATA ENTREGA", "VALOR"
            }
        ));
        jScrollPane1.setViewportView(jTablePedido);

        jButtonSair.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSair.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSair.setText("SAIR");

        jButtonBuscar_Pedido.setBackground(new java.awt.Color(0, 204, 255));
        jButtonBuscar_Pedido.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonBuscar_Pedido.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBuscar_Pedido.setText("BUSCAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCod_Pedido)
                            .addComponent(jButtonId_cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonData_Entrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonData_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(272, 272, 272))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel2)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)))
                        .addComponent(jButtonBuscar_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jButtonSair))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonData_Pedido)
                    .addComponent(jButtonCod_Pedido))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonData_Entrega)
                    .addComponent(jButtonId_cliente))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar_Pedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSair)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultaPedido().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar_Pedido;
    private javax.swing.JButton jButtonCod_Pedido;
    private javax.swing.JButton jButtonData_Entrega;
    private javax.swing.JButton jButtonData_Pedido;
    private javax.swing.JButton jButtonId_cliente;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePedido;
    private javax.swing.JTextField jTextFieldObjeto;
    // End of variables declaration//GEN-END:variables
}
