
package view;

/**
 *
 * @author vitor
 */
public class ExcluirPedidoView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExcluirPedidoView.class.getName());
    private final Controller.PedidoController pedidoCtrl = new Controller.PedidoController();

    // Creates new form ExcluirPedidoView
    
    public ExcluirPedidoView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** Carrega o pedido na tabela. */
    private void buscarPedidoParaExcluir() {
        String codStr = jTextFieldCod_pedido.getText().trim();
        if (codStr.isEmpty()) return;
        try {
            int cod = Integer.parseInt(codStr);
            model.Pedido p = pedidoCtrl.consultar(cod);
            javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) jTableExcluirPedido.getModel();
            modelo.setRowCount(0);
            
            // Limpa itens
            ((javax.swing.table.DefaultTableModel) jTableExcluirItem.getModel()).setRowCount(0);

            if (p == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pedido " + cod + " não encontrado.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            } else {
                modelo.addRow(new Object[]{ 
                    p.getCodPedido(), p.getIdCliente(), p.getDtPedido(), p.getDtEntrega(), String.format("R$ %.2f", p.getVlrTotal()) 
                });
            }
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Código inválido.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCod_pedido = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jButtonRetornar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableExcluirPedido = new javax.swing.JTable();
        jButtonBuscar_pedido = new javax.swing.JButton();
        jButtonSelecionarPedido = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableExcluirItem = new javax.swing.JTable();
        jButtonConsultarPedido = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("EXCLUSÃO PEDIDO");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("CODIDO PEDIDO");

        jTextFieldCod_pedido.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCod_pedido.addActionListener(this::jTextFieldCod_pedidoActionPerformed);

        jButtonExcluir.setBackground(new java.awt.Color(255, 51, 51));
        jButtonExcluir.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(this::jButtonExcluirActionPerformed);

        jButtonRetornar.setBackground(new java.awt.Color(0, 153, 255));
        jButtonRetornar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonRetornar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRetornar.setText("RETORNAR");
        jButtonRetornar.addActionListener(this::jButtonRetornarActionPerformed);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("TABELA ITENS");

        jTableExcluirPedido.setBackground(new java.awt.Color(204, 204, 204));
        jTableExcluirPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo Pedido", "ID Cliente", "Data Pedido", "Data Entrega", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableExcluirPedido);

        jButtonBuscar_pedido.setBackground(new java.awt.Color(0, 153, 255));
        jButtonBuscar_pedido.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonBuscar_pedido.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar_pedido.setText("BUSCAR");
        jButtonBuscar_pedido.addActionListener(this::jButtonBuscar_pedidoActionPerformed);

        jButtonSelecionarPedido.setBackground(new java.awt.Color(0, 153, 255));
        jButtonSelecionarPedido.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonSelecionarPedido.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSelecionarPedido.setText("SELECIONAR");
        jButtonSelecionarPedido.addActionListener(this::jButtonSelecionarPedidoActionPerformed);

        jTableExcluirItem.setBackground(new java.awt.Color(204, 204, 204));
        jTableExcluirItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Pedido", "Sequencia Item", "Codigo Produto", "Quantidade", "Preco unidade", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableExcluirItem);

        jButtonConsultarPedido.setBackground(new java.awt.Color(0, 153, 255));
        jButtonConsultarPedido.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonConsultarPedido.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarPedido.setText("CONSULTAR");
        jButtonConsultarPedido.addActionListener(this::jButtonConsultarPedidoActionPerformed);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("TABELA PEDIDO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButtonExcluir)
                        .addGap(161, 161, 161)
                        .addComponent(jButtonRetornar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCod_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscar_pedido)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonConsultarPedido))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jButtonSelecionarPedido))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCod_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar_pedido)
                    .addComponent(jButtonConsultarPedido))
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSelecionarPedido)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonRetornar))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCod_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCod_pedidoActionPerformed
        buscarPedidoParaExcluir();
    }//GEN-LAST:event_jTextFieldCod_pedidoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTableExcluirPedido.getModel();
        if (modelo.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Busque um pedido primeiro.");
            return;
        }
        int codPedido = Integer.parseInt(modelo.getValueAt(0, 0).toString());
        
        int op = javax.swing.JOptionPane.showConfirmDialog(this, "Excluir o pedido " + codPedido + " e todos os seus itens? Isso atualizará o estoque.", "Confirmar Exclusão", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);
        if (op == javax.swing.JOptionPane.YES_OPTION) {
            String erro = pedidoCtrl.excluir(codPedido);
            if (erro.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pedido excluído com sucesso!");
                modelo.setRowCount(0);
                ((javax.swing.table.DefaultTableModel) jTableExcluirItem.getModel()).setRowCount(0);
                jTextFieldCod_pedido.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, erro, "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornarActionPerformed
        new view.PedidoPrincipalView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRetornarActionPerformed

    private void jButtonBuscar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscar_pedidoActionPerformed
        buscarPedidoParaExcluir();
    }//GEN-LAST:event_jButtonBuscar_pedidoActionPerformed

    private void jButtonSelecionarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarPedidoActionPerformed
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTableExcluirPedido.getModel();
        if (modelo.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Busque um pedido primeiro.");
            return;
        }
        int codPedido = Integer.parseInt(modelo.getValueAt(0, 0).toString());
        
        javax.swing.table.DefaultTableModel modeloItem = (javax.swing.table.DefaultTableModel) jTableExcluirItem.getModel();
        modeloItem.setRowCount(0);
        
        Controller.ItemController itemCtrl = new Controller.ItemController();
        for (model.Item it : itemCtrl.listarPorPedido(codPedido)) {
            modeloItem.addRow(new Object[]{
                it.getCodPedido(),
                it.getSeqItem(),
                it.getCodProduto(),
                it.getQtdeItens(),
                String.format("R$ %.2f", it.getPrecoUnitario()),
                String.format("R$ %.2f", it.getPrecoTotal())
            });
        }
    }//GEN-LAST:event_jButtonSelecionarPedidoActionPerformed

    private void jButtonConsultarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarPedidoActionPerformed
        new view.ConsultaPedido().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonConsultarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ExcluirPedidoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar_pedido;
    private javax.swing.JButton jButtonConsultarPedido;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonRetornar;
    private javax.swing.JButton jButtonSelecionarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableExcluirItem;
    private javax.swing.JTable jTableExcluirPedido;
    private javax.swing.JTextField jTextFieldCod_pedido;
    // End of variables declaration//GEN-END:variables
}
