
package view;

import model.Item;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author conta
 */
public class ItemView extends javax.swing.JFrame {
    
    // ItemController é o controlador responsável pelas operações de item
    private final Controller.ItemController itemCtrl = new Controller.ItemController();
    private final Controller.ProdutoController prodCtrl = new Controller.ProdutoController();
    private int codPedidoAtual; //guardar o codigo do pedido aqui
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ItemView.class.getName());

    //Construtor que recebe o código do pedido de itens
    
    public ItemView(int codPedido) {
        initComponents();
        this.codPedidoAtual = codPedido;           // guarda o código do pedido
        txtCodPedido.setText(String.valueOf(codPedido));
        lblInfoPedido.setText("Itens do Pedido PED-" + codPedido);
        this.setLocationRelativeTo(null);
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblTituloSecao = new javax.swing.JLabel();
        lblCodPedido = new javax.swing.JLabel();
        txtCodPedido = new javax.swing.JTextField();
        lblSeq = new javax.swing.JLabel();
        lblCodProduto = new javax.swing.JLabel();
        txtPrecoUnitario = new javax.swing.JTextField();
        txtSeqItem = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        lblQuantidade1 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnRemover = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblInfoPedido = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        pnlValorTotal = new javax.swing.JPanel();
        lblValorTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 244, 244));
        setPreferredSize(new java.awt.Dimension(970, 690));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTituloSecao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloSecao.setForeground(new java.awt.Color(0, 102, 204));
        lblTituloSecao.setText("DADOS DO ITEM");

        lblCodPedido.setText("Cód. Pedido");

        txtCodPedido.setEditable(false);
        txtCodPedido.setBackground(new java.awt.Color(255, 255, 255));
        txtCodPedido.setForeground(new java.awt.Color(100, 100, 100));
        txtCodPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        txtCodPedido.setPreferredSize(new java.awt.Dimension(150, 30));

        lblSeq.setText("Sequência");

        lblCodProduto.setText("Cód. Produto");

        txtPrecoUnitario.setEditable(false);
        txtPrecoUnitario.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecoUnitario.setForeground(new java.awt.Color(100, 100, 100));
        txtPrecoUnitario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        txtPrecoUnitario.setPreferredSize(new java.awt.Dimension(120, 30));

        txtSeqItem.setEditable(false);
        txtSeqItem.setBackground(new java.awt.Color(255, 255, 255));
        txtSeqItem.setForeground(new java.awt.Color(100, 100, 100));
        txtSeqItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        txtSeqItem.setPreferredSize(new java.awt.Dimension(60, 30));

        lblQuantidade.setText("Quantidade");

        txtCodProduto.setBackground(new java.awt.Color(255, 255, 255));
        txtCodProduto.setForeground(new java.awt.Color(100, 100, 100));
        txtCodProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        txtCodProduto.setPreferredSize(new java.awt.Dimension(200, 30));

        lblQuantidade1.setText("Preço Unitário");

        txtQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantidade.setForeground(new java.awt.Color(100, 100, 100));
        txtQuantidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        txtQuantidade.setPreferredSize(new java.awt.Dimension(80, 30));

        btnRemover.setBackground(new java.awt.Color(255, 255, 255));
        btnRemover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(204, 0, 0));
        btnRemover.setText("Remover");
        btnRemover.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRemover.setPreferredSize(new java.awt.Dimension(140, 35));
        btnRemover.addActionListener(this::btnRemoverActionPerformed);

        btnAdicionar.setBackground(new java.awt.Color(0, 102, 204));
        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdicionar.setPreferredSize(new java.awt.Dimension(140, 35));
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpar.setPreferredSize(new java.awt.Dimension(140, 35));
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblInfoPedido.setForeground(new java.awt.Color(102, 102, 102));
        lblInfoPedido.setText("Itens do Pedido PED-XXXX");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblInfoPedido)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodPedido)
                            .addComponent(txtCodPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSeqItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeq))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodProduto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantidade))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuantidade1)
                            .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTituloSecao))
                .addContainerGap(146, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloSecao)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuantidade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCodPedido)
                                .addComponent(lblSeq)
                                .addComponent(lblCodProduto)
                                .addComponent(lblQuantidade1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSeqItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Seq.", "Cód. Produto", "Descrição do Produto", "Qtd.", "Preço Unitário", "Preço Total"
            }
        ));
        jScrollPane2.setViewportView(tblItens);
        if (tblItens.getColumnModel().getColumnCount() > 0) {
            tblItens.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblItens.getColumnModel().getColumn(0).setMaxWidth(70);
            tblItens.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblItens.getColumnModel().getColumn(1).setMaxWidth(120);
            tblItens.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblItens.getColumnModel().getColumn(4).setPreferredWidth(80);
            tblItens.getColumnModel().getColumn(5).setPreferredWidth(80);
        }

        pnlValorTotal.setBackground(new java.awt.Color(0, 86, 179));
        pnlValorTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblValorTotal.setText("Valor Total do Pedido");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("R$");

        javax.swing.GroupLayout pnlValorTotalLayout = new javax.swing.GroupLayout(pnlValorTotal);
        pnlValorTotal.setLayout(pnlValorTotalLayout);
        pnlValorTotalLayout.setHorizontalGroup(
            pnlValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValorTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValorTotal)
                    .addComponent(jLabel1))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        pnlValorTotalLayout.setVerticalGroup(
            pnlValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValorTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValorTotal)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        try{
            int codProd =Integer.parseInt(txtCodProduto.getText());
            int qtd = Integer.parseInt(txtQuantidade.getText());

            String erro = itemCtrl.incluir(codPedidoAtual, codProd, qtd);

            if (erro.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Item adicionado!");
                carregarTabela();
                limparCampos();
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, erro, "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch(NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,"Informe códigos e quantidades válidas.");
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        int linha = tblItens.getSelectedRow();
        if(linha == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um item na tabela.");
            return;
        }

        int seq = (int)tblItens.getValueAt(linha, 0);
        
        int op = javax.swing.JOptionPane.showConfirmDialog(this, "Excluir item " + seq + "?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
        if (op == javax.swing.JOptionPane.YES_OPTION) {
            itemCtrl.excluir(codPedidoAtual, seq);
            carregarTabela();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }
    private void limparCampos() {
        txtCodProduto.setText("");
        txtQuantidade.setText("");
        txtPrecoUnitario.setText("");
        txtCodProduto.requestFocus();
    }
    
    private void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tblItens.getModel();
        modelo.setRowCount(0);
        List<Item> itens = itemCtrl.listarPorPedido(codPedidoAtual);
        double totalPedido = 0;
        for (Item item : itens) {
            model.Produto p = prodCtrl.consultar(item.getCod_produto());
            String desc = p != null ? p.getNome() : "Desconhecido";
            modelo.addRow(new Object[]{
                item.getSeq_item(),
                item.getCod_produto(),
                desc,
                item.getQtde_itens(),
                String.format("R$ %.2f", item.getPreco_uniItem()),
                String.format("R$ %.2f", item.getPreco_total())
            });
            totalPedido += item.getPreco_total();
        }
        lblValorTotal.setText(String.format("R$ %.2f", totalPedido));
    }
    //GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // Para testar, abre com pedido de código 1 como exemplo
        java.awt.EventQueue.invokeLater(() -> new ItemView(1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCodPedido;
    private javax.swing.JLabel lblCodProduto;
    private javax.swing.JLabel lblInfoPedido;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblQuantidade1;
    private javax.swing.JLabel lblSeq;
    private javax.swing.JLabel lblTituloSecao;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel pnlValorTotal;
    private javax.swing.JTable tblItens;
    private javax.swing.JTextField txtCodPedido;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JTextField txtPrecoUnitario;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtSeqItem;
    // End of variables declaration//GEN-END:variables
}
