package view;

/**
 *
 * @author vitor
 */
public class PedidoPrincipalView extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PedidoPrincipalView.class.getName());

    
    public PedidoPrincipalView() {
        initComponents();
        this.setLocationRelativeTo(null);
        configurarBotoes();
    }

    private void configurarBotoes() {
        jButtonNovoPedido.addActionListener(e -> { new incluirPedido().setVisible(true); this.dispose(); });
        jButtonAlterar.addActionListener(e -> { new AlterarPedidoView().setVisible(true); this.dispose(); });
        jButtonListar.addActionListener(e -> { new ListarPedido().setVisible(true); this.dispose(); });
        jButtonConsultar.addActionListener(e -> { new ConsultaPedido().setVisible(true); this.dispose(); });
        jButtonExcluir1.addActionListener(e -> { new ExcluirPedidoView().setVisible(true); this.dispose(); });
        jButtonrRetornar.addActionListener(e -> { this.dispose(); }); // Sai do menu de pedidos
    }
    private void btnNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {
        new incluirPedido().setVisible(true);
        this.dispose();
    }

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {
        new AlterarPedidoView().setVisible(true);
        this.dispose();
    }

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {
        new ConsultaPedido().setVisible(true);
        this.dispose();
    }

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {
        new ExcluirPedidoView().setVisible(true);
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonNovoPedido = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonListar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonExcluir1 = new javax.swing.JButton();
        jButtonrRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("MENU PEDIDO");

        jButtonNovoPedido.setBackground(new java.awt.Color(102, 102, 102));
        jButtonNovoPedido.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButtonNovoPedido.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNovoPedido.setText("NOVO PEDIDO");

        jButtonAlterar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonAlterar.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButtonAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAlterar.setText("ALTERAR");

        jButtonListar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonListar.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButtonListar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListar.setText("LISTAR");

        jButtonConsultar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonConsultar.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButtonConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultar.setText("CONSULTAR");

        jButtonExcluir1.setBackground(new java.awt.Color(102, 102, 102));
        jButtonExcluir1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButtonExcluir1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir1.setText("EXCLUIR");

        jButtonrRetornar.setBackground(new java.awt.Color(255, 0, 0));
        jButtonrRetornar.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButtonrRetornar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonrRetornar.setText("RETORNAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonListar)
                            .addComponent(jButtonNovoPedido)
                            .addComponent(jButtonAlterar)
                            .addComponent(jButtonConsultar)
                            .addComponent(jButtonExcluir1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButtonrRetornar)))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonNovoPedido)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterar)
                .addGap(29, 29, 29)
                .addComponent(jButtonListar)
                .addGap(30, 30, 30)
                .addComponent(jButtonExcluir1)
                .addGap(30, 30, 30)
                .addComponent(jButtonConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButtonrRetornar)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PedidoPrincipalView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonExcluir1;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonNovoPedido;
    private javax.swing.JButton jButtonrRetornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
